name: C MESON CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install deps
      run: sudo apt install meson gnome-pkg-tools libcanberra-dev itstool libgirepository1.0-dev libgnome-autoar-0-dev libgoa-1.0-dev libgspell-1-dev libgtk-3-dev libjson-glib-dev librest-dev libsoup-gnome2.4-dev meson pkg-config
    - name: clean build
      run: rm -rf build
    - name: meson prefix
      run: meson --prefix /usr build
    - name: ninja build
      run: ninja -C build
